// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTt5UQ6Ynam7xXF-_8IUVyIOHcTPuiRFo',
    appId: '1:839751815101:android:e02a87ce23dd468e028cd4',
    messagingSenderId: '839751815101',
    projectId: 'expiry-date-d0fed',
    storageBucket: 'expiry-date-d0fed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbnOjbuk6GGOVoZ08xwtbGVUD_pK1LtP8',
    appId: '1:839751815101:ios:f2a1535ae71e9675028cd4',
    messagingSenderId: '839751815101',
    projectId: 'expiry-date-d0fed',
    storageBucket: 'expiry-date-d0fed.firebasestorage.app',
    iosClientId: '839751815101-q7kvfl6ecbrc7ptfnq6vgu8c1bejg6dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.expiryDate',
  );
}
